### ISSUE TITLE
Mapa mental Web 3.0

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/mapa-mental-web-3-Brisa-4#1]
[Mapa mental IS.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Brisa-4/files/8401567/Mapa.mental.IS.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
